### ISSUE TITLE
Implement ways to put notebooks (and lakehouse) under version control, at least make it easier to save code locally

### ISSUE THREAD

**Issue by aisbergde** [microsoft/SynapseVSCode#10]
It is possible, to access the local notebook, using the "Reveal in File explorer". This works.

There could be a more intuitive way, for example: "export notebook" or a "save as" or a "save locally", instead of browsing to the working folder in the file explorer.

And it would be great if we could store notebooks (and other stuff) under source control. Maybe, this is already on the roadmap, because a workspace already can be connected to an Azure DevOps git repository. But currently only Power BI reports are under source control. For me, it is essential, to have all my development under source control. Currently, it is hard or even impossible to have fabric development under source control.

The extension shows Lakehouse tables. Hoovering over tables, there is even a tooltip. But the tooltip is only shown, the content can't be used, can't be copied. This could be improved.

It would be fine if we would be able to create some code, which will create the table (sql, PySpark), In SSMS I can generate scripts to generate tables. Something like this would be very helpful.

In General it would be even better, if the online GUI for lakehouse and notebooks would be improved. To enable to save (export?) notebooks as file, lakehouse tables as script, and so on.

**Comment by qixwang** [comment]
@aisbergde apologize for the late reply, please check the update/answer as below 

for the version control part, it is under the roadmap and actually the notebook will be supported with Git very soon. similarly as PowerBi Report, you can put your notebook under version control via the Git support in the portal. 

for the tooltip part, thanks for the suggestion, we will consider it in our next integration, also we would consider the feedback around directly generating some code from the lakehouse/table.
