### ISSUE TITLE
Preparing synapse pyspark env...  'conda' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by jcbendernh** [microsoft/SynapseVSCode#12]
When I open a Fabric notebook in Visual Studio Code via the Open VS Code button in Fabric, I am now getting the error below and I cannot access the Fabric Kernel in VS Code.  This worked last month.  How can I resolve it?

Preparing synapse pyspark env...
'conda' is not recognized as an internal or external command,
operable program or batch file.

**Comment by jcbendernh** [comment]
conda is recognized in the PowerShell terminal within VS Code.  See screenshot for reference.

![Screenshot 2023-08-03 114344](https://github.com/microsoft/SynapseVSCode/assets/16260984/3dd5ef9d-5981-4407-9e99-951936bf165f)

**Comment by jcbendernh** [comment]
Issue seems to be resolved with a new version of the Synapse Spark IDE environment.  It was either that or restrictions on the client's guest network.

**Comment by Robmattles** [comment]
I am seeing the same issue with the current version of the Synapse Spark IDE environment
