### ISSUE TITLE
Synapse/Fabric Kernel is not available in VS Code.

### ISSUE THREAD

**Issue by jcbendernh** [microsoft/SynapseVSCode#13]
When I am working on a notebook in Fabric and I click the Open in VS code button, it downloads and activates in VS Code, but I do not have a Fabric option under the Change Kernel option in VS Code, even though I see the following message in the OUTPUT tab...

_Check if synapse spark kernel env has created... true
Download C:\Users\jobender\AppData\Local\miniconda3\envs\synapse-spark-kernel\lib\site-packages\delta.pth script completed, download to C:\Users\jobender\AppData\Local\miniconda3\envs\synapse-spark-kernel\lib\site-packages\delta.pth
The synapse spark kernel env has been created, skip the creation process of conda env.
The lighter Lib already exists and the version meets requirement, skip download.
The Synapse PySpark environment preparation is complete! Now, please switch your kernel to start exploring and working with it!_

How can I resolve this error?  See screenshot for reference.

![Screenshot 2023-08-05 082104](https://github.com/microsoft/SynapseVSCode/assets/16260984/2fc57cb9-b20c-4591-8102-86b2a1c2401d)

**Comment by crazy4pi314** [comment]
I can get to the same point, but I think I found the right kernel. If you look under Python environments, and then you should see the `synapse-spark-kernel` option, which is the one the extension creates. Hope that helps!

**Comment by ayzmkk-rongbi** [comment]
Thanks @crazy4pi314 for the comment :). @jcbendernh You can also press `Ctrl + Shift + P` and choose the Python: Select Interpreter command and enter "/path/to/conda/envs/synapse-spark-kernel/python
![image](https://github.com/microsoft/SynapseVSCode/assets/73167059/605c5460-b082-4293-abf4-f609a743aa96)
![image](https://github.com/microsoft/SynapseVSCode/assets/73167059/ac98f431-f4a6-457e-b871-cab3c52f65bd)
