### ISSUE TITLE
Spark not initializing in local conda env 

### ISSUE THREAD

**Issue by crazy4pi314** [microsoft/SynapseVSCode#15]
I have run into the issue that a notebook that I create/use in the web portal for Synapse Data Science seems to be missing environment initialization locally that happens on the web.

Steps:
1. Create a data science notebook in the web portal for Fabric, connect a Data Lake with data in it.
2. Right click a data file in the lake and choose `load data > Spark`
<img width="530" alt="image" src="https://github.com/microsoft/SynapseVSCode/assets/6486256/fa08c6fd-beb4-434e-bccd-ebf0391137d4">
3. Run the cell that is inserted into the code and see that it loads the data correctly:
<img width="1049" alt="image" src="https://github.com/microsoft/SynapseVSCode/assets/6486256/17ec3e8b-fc4d-46d2-9ae9-367fbafeeb7a">
4. Click the tool bar button to open the notebook in VS Code (have the Synapse extension already installed) and confirm opening the notebook.
5. Select the conda env created by the extension () for the newly opened notebook:
<img width="901" alt="image" src="https://github.com/microsoft/SynapseVSCode/assets/6486256/53e1d47d-725f-43ed-886f-09d94002d5fc">
6. Try running the same cell to load the spark frame and you get an attribute error:
<img width="1200" alt="image" src="https://github.com/microsoft/SynapseVSCode/assets/6486256/9a2ba5db-5ec6-46f7-a9fd-d50f63364055">

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 1
----> 1 df = spark.read.format("csv").option("header","true").load("Files/Manateetracking/NW_GOM_manatee_habitat_data.csv")
      2 # df now is a Spark DataFrame containing CSV data from "Files/Manateetracking/NW_GOM_manatee_habitat_data.csv".
      3 display(df)

AttributeError: 'NoneType' object has no attribute 'read'
```
I also checked that the other UI suggested way of loading Lakehouse data with Pandas works in the web based notebook, but the Pandas package is not installed in the local conda env created with the extension:
<img width="855" alt="image" src="https://github.com/microsoft/SynapseVSCode/assets/6486256/1bcd9f01-dd8b-4485-8c62-92849da77c09">

Happy to grab more screenshots, but my main goal is to work on the same notebook that is in the web portal locally (in a Dev Container if possible to make the JDK requirement easy)

Thanks!

**Comment by ayzmkk-rongbi** [comment]
Hi @crazy4pi314 Thank you for reporting this issue.
Could you provide the python log to us?
1) Go to Local Work Folder 2) Go to logs folder 3) Go to the specific notebook artifact folder named by notebook artifact id 4) Show the PySparkLighter.log
![image](https://github.com/microsoft/SynapseVSCode/assets/73167059/c5b82859-231d-4e9b-95fd-d690b97dbfaa)

We don't have pandas as a hard dependency of the local conda env. It will not be installed automatically when creating env. But we will try to keep it consistent with the fabric runtime package in the dev container. (We can try the dev container synchronously offline. But we haven't released it yet.)

**Comment by crazy4pi314** [comment]
The log file, I will double check my jdk install is ok, but that is part of why I started working in a DevContainer bc I don't trust any machine local state :)
```log
00:58:28,363 root INFO Using synapse remote kernel ...
00:58:28,387 root INFO Should attach session in dev mode False
00:58:28,884 root INFO Starting session 1543b35e-acc5-46c9-aa76-a180b8067954...
00:58:37,469 root INFO https://pbipmsitwcus22-msit.pbidedicated.windows.net/webapi/capacities/F6B87806-0697-4974-BEA2-125CAEB71A13/workloads/Notebook/Data/Direct/sparklighter/api/tjs/versions/2022-04-30/artifacts/3a036ea4-abd3-4a73-a91d-8841b046b866/sessions/1543b35e-acc5-46c9-aa76-a180b8067954
00:58:39,70 root INFO <session_management.SessionStatus object at 0x0000020705130970>
00:58:44,719 root INFO Trident session states: idle
00:58:44,729 root INFO Starting session 1543b35e-acc5-46c9-aa76-a180b8067954 finished...
00:58:44,729 root INFO Attaching spark session 1543b35e-acc5-46c9-aa76-a180b8067954 for Spark Lighter ...
00:58:46,552 root ERROR Failed to initialize Spark Lighter variables. Java gateway process exited before sending its port number
00:58:46,552 root INFO Registering Spark Lighter magics for IPython...
00:58:46,552 root INFO Registered Spark Lighter magics for IPython.
01:15:47,654 root INFO Using synapse remote kernel ...
01:15:47,683 root INFO Should attach session in dev mode False
01:15:47,949 root INFO Starting session 84fd5121-1a72-464d-a763-3de26c36d67d...
01:15:50,906 root INFO https://pbipmsitwcus22-msit.pbidedicated.windows.net/webapi/capacities/F6B87806-0697-4974-BEA2-125CAEB71A13/workloads/Notebook/Data/Direct/sparklighter/api/tjs/versions/2022-04-30/artifacts/3a036ea4-abd3-4a73-a91d-8841b046b866/sessions/84fd5121-1a72-464d-a763-3de26c36d67d
01:15:53,623 root INFO <session_management.SessionStatus object at 0x00000195B77C0970>
01:15:57,600 root INFO Trident session states: busy
01:16:03,966 root INFO Trident session states: busy
01:16:11,230 root INFO Trident session states: idle
01:16:11,236 root INFO Starting session 84fd5121-1a72-464d-a763-3de26c36d67d finished...
01:16:11,236 root INFO Attaching spark session 84fd5121-1a72-464d-a763-3de26c36d67d for Spark Lighter ...
01:16:13,17 root ERROR Failed to initialize Spark Lighter variables. Java gateway process exited before sending its port number
01:16:13,17 root INFO Registering Spark Lighter magics for IPython...
01:16:13,17 root INFO Registered Spark Lighter magics for IPython.
01:16:36,977 root INFO Using synapse remote kernel ...
01:16:36,990 root INFO Should attach session in dev mode False
01:16:37,719 root INFO Starting session 8a5fa6be-17fe-4fc0-bfe7-b20efc89a454...
01:16:41,28 root INFO https://pbipmsitwcus22-msit.pbidedicated.windows.net/webapi/capacities/F6B87806-0697-4974-BEA2-125CAEB71A13/workloads/Notebook/Data/Direct/sparklighter/api/tjs/versions/2022-04-30/artifacts/3a036ea4-abd3-4a73-a91d-8841b046b866/sessions/8a5fa6be-17fe-4fc0-bfe7-b20efc89a454
01:16:42,552 root INFO <session_management.SessionStatus object at 0x000001ECB4240430>
01:16:46,335 root INFO Trident session states: idle
01:16:46,341 root INFO Starting session 8a5fa6be-17fe-4fc0-bfe7-b20efc89a454 finished...
01:16:46,341 root INFO Attaching spark session 8a5fa6be-17fe-4fc0-bfe7-b20efc89a454 for Spark Lighter ...
01:16:47,700 root ERROR Failed to initialize Spark Lighter variables. Java gateway process exited before sending its port number
01:16:47,702 root INFO Registering Spark Lighter magics for IPython...
01:16:47,703 root INFO Registered Spark Lighter magics for IPython.
01:17:20,750 root INFO Using synapse remote kernel ...
01:17:20,774 root INFO Should attach session in dev mode False
01:17:21,34 root INFO Starting session 3771af0e-62f3-4973-8ed9-8efce3bea1c4...
01:17:24,40 root INFO https://pbipmsitwcus22-msit.pbidedicated.windows.net/webapi/capacities/F6B87806-0697-4974-BEA2-125CAEB71A13/workloads/Notebook/Data/Direct/sparklighter/api/tjs/versions/2022-04-30/artifacts/3a036ea4-abd3-4a73-a91d-8841b046b866/sessions/3771af0e-62f3-4973-8ed9-8efce3bea1c4
01:17:25,544 root INFO <session_management.SessionStatus object at 0x000002403EC70430>
01:17:29,8 root INFO Trident session states: idle
01:17:29,15 root INFO Starting session 3771af0e-62f3-4973-8ed9-8efce3bea1c4 finished...
01:17:29,15 root INFO Attaching spark session 3771af0e-62f3-4973-8ed9-8efce3bea1c4 for Spark Lighter ...
01:17:30,224 root ERROR Failed to initialize Spark Lighter variables. Java gateway process exited before sending its port number
01:17:30,224 root INFO Registering Spark Lighter magics for IPython...
01:17:30,224 root INFO Registered Spark Lighter magics for IPython.
```

**Comment by crazy4pi314** [comment]
Update: I uninstalled and re-installed all Java/JDK tools on my system and that seems to have fixed the failing Java gateway process, and I was able to run the spark cells (intellisense still didn't have info on the spark package somehow though). I'll test some more now, but at least the basic setup seems to be working! <3

I think this makes a good argument for Dev Containers, to make sure the JDK setup is correct and reproducable across platforms/OS 💪

**Comment by ayzmkk-rongbi** [comment]
@crazy4pi314  Thanks :) we are working on this
