### ISSUE TITLE
mssparkutils are still not packaged as of 1.2.0

### ISSUE THREAD

**Issue by LillyBeast-TMO** [microsoft/SynapseVSCode#16]

**Comment by qixwang** [comment]
@LillyBeast-TMO thanks for the feedback, some of the core feature of the mspsarkutil such as running a notebook from another notebook is not supported yet in local, we don't have any ETA yet for this update.

**Comment by qixwang** [comment]
@LillyBeast-TMO thanks for the feedback, some of the core feature of the mspsarkutil such as running a notebook from another notebook is not supported yet in local, we don't have any ETA yet for this update.

**Comment by LillyBeast-TMO** [comment]
Are you saying that since some of the mssparkutils functionality is not suppoted in local, **and since mssparkutils are always local**, you are not planning to package mssparkutils at all?
That sounds like a pretty big limitation, no? Essentially, none of the notebooks that use mssaprkutils can work using this extension,  right?
