### ISSUE TITLE
Update link to Java 8 JDK

### ISSUE THREAD

**Issue by andrewluotechnologies** [microsoft/SynapseVSCode#18]
The overview page in the [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=SynapseVSCode.synapse&ssr=false#overview) includes JDK 1.8 as a requirement however the link points to outdated/old version of the Oracle JDK.  Updated versions are not available because of changes in Oracle licensing, so I would suggest linking to another JDK, perhaps Adoptium which can be installed with winget also (`winget install --id=AdoptOpenJDK.OpenJDK.8 -e`)

**Comment by andrewluotechnologies** [comment]
Additionally it would be nice if the plugin could support a newer JDK version, such as 17

**Comment by qixwang** [comment]
@andrewluotechnologies  thanks for the feedback, we changed the java version now to OpendJDK8. later on, we will support more version.
