### ISSUE TITLE
Error when creating Synapse IDE

### ISSUE THREAD

**Issue by klinejordan** [microsoft/SynapseVSCode#3]
Check if synapse spark kernel env has created... false
Prepare synapse-spark-kernel env.
Current user Agent is node/16.17.1 (windows_nt 10.0.22000; win32; x64)
init conda C:\Program Files\Anaconda3\scripts\activate.bat C:\Program Files\Anaconda3
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

Preparing synapse spark conda env failed
Installing PySpark releated packages error

**Comment by ayzmkk-rongbi** [comment]
Hi @klinejordan, thanks for providing this issue :)
Please upgrade this extension to version 0.3.0 to resolve this issue.
