### ISSUE TITLE
Error Loading Extention

### ISSUE THREAD

**Issue by muhssamy** [microsoft/SynapseVSCode#36]
when i try to use the extension after version 1.9.0 i got this issue

![image](https://github.com/microsoft/SynapseVSCode/assets/49695385/5d61b696-efc8-4b2f-b8c8-1d032f9f22e7)

**Comment by realDuang** [comment]
Sorry for the delay. The issue has been fixed in the latest version of extension. Please feel free to try to see if it happen again.
