### ISSUE TITLE
cannot read properties of null (reading 'name')

### ISSUE THREAD

**Issue by mh-hassan18** [microsoft/SynapseVSCode#40]
I am not able to fetch any notebooks from my fabric workspace. When I click on Notebooks dropdown I get "cannot read properties of null (reading 'name')". Lakehouses are working fine though. 

Synapse VS Code version: 1.9.0
VS Code version: 1.92.2

**Comment by realDuang** [comment]
Sorry for the delay. The issue has been fixed in the latest version of extension. Please feel free to try to see if it happen again.
