### ISSUE TITLE
'conda' is not a recognized command

### ISSUE THREAD

**Issue by Robmattles** [microsoft/SynapseVSCode#45]
I'm receiving the following message whenever I try to open a Fabric notebook in VsCode

Preparing synapse pyspark env...
'conda' is not recognized as an internal or external command,
operable program or batch file.

The Synapse PySpark environment preparation failed: undefined
Installing PySpark releated packages error

**Comment by realDuang** [comment]
Hi @Robmattles, It looks like you don't have conda installed, please make sure you follow the Prerequisites steps in the documentation to prepare it correctly?

https://review.learn.microsoft.com/en-us/fabric/data-engineering/setup-vs-code-extension?branch=main&branchFallbackFrom=release-public-preview
