### ISSUE TITLE
Can't select Tenant for Synapse VS Code extension

### ISSUE THREAD

**Issue by NonlinearMusings** [microsoft/SynapseVSCode#5]
My Trident tenant is not the same as my Microsoft tenant and the Synapse VS Code extension does not let me designate the tenant. Rather it auto-assigns my Microsoft identity and logs me in, incorrectly. Secondarily, my Trident tenant does not have an Azure Subscription - it's M365 - so that dependency it's helpful either.

**Comment by ayzmkk-rongbi** [comment]
@NonlinearMusings  Thanks for your comment. Can u please try to sign out the account in Edge
![image](https://github.com/microsoft/SynapseVSCode/assets/73167059/cfbe4934-2d10-48a0-980d-274cd5a4dac5)
And type `Ctrl + Shift + P` to do Synapse: Sign out and Synapse: Sign in again? It could let you input another account.
