### ISSUE TITLE
'NoneType' object has no attribute 'sql'

### ISSUE THREAD

**Issue by GMedlin** [microsoft/SynapseVSCode#8]
I followed the getting started instructions, installed the prerequisites, selected the included kernel, and tried to run my notebook in VS Code on Windows. I get an error locally, but my notebook runs fine in fabric.

**Code**
```
`# Welcome to your new notebook
# Type here in the cell editor to add code!

df = spark.sql("SELECT * FROM SalesLakehouse.DimCustomer LIMIT 1000")
display(df)`
```

**This is the error message:**

AttributeError                            Traceback (most recent call last)
Cell In[1], line 4
      1 # Welcome to your new notebook
      2 # Type here in the cell editor to add code!
----> 4 df = spark.sql("SELECT * FROM SalesLakehouse.DimCustomer LIMIT 1000")
      5 display(df)

AttributeError: 'NoneType' object has no attribute 'sql'

**Screenshot**
![image](https://github.com/microsoft/SynapseVSCode/assets/13262106/4093a64a-3585-46b3-a5c3-4c6924d87646)

**Comment by crazy4pi314** [comment]
I have run into this as well, and iiuc spark is auto-imported in the fabric environment, but the extension make a local conda env that you need to import packages manually.

**Comment by crazy4pi314** [comment]
I filed a related issue #15, might be able to track down something in common causing this 👍
