### ISSUE TITLE
merging notebooks doesn't allow reverting local changes and keeping remote changes. We need merge control

### ISSUE THREAD

**Issue by aisbergde** [microsoft/SynapseVSCode#9]
My scenario:

- I load a notebook into the extension
- I did not publish, because ..., because I wan't to decide, how to merge and what and when to publish
- I closed VSC and my PC
- I changed the notebook online in fabric
- I open VCS and connect to fabric again
- my local notbook is older, and I wan't to use the remote content, but I can't. There is only an automated merge, which will overwirte the remote notebook.

=> there should be some options, when merging. I should be able to select, if I want to use the remote content or the local content. I also should be able to undo local changes. In general, I want to work, as I work with git.

Currently, it is even dangerous to use the extension, because it could overwrite my remote content, when I don't want this to happen. 

We are developers - give us control over the merge process, instead of doing automated (and sometimes wrong) decisions.

**Comment by realDuang** [comment]
@aisbergde  Thanks for your helpful feedback!
Synchronous experience has always been a concern for us. But the situation here is a little complicated. On the one hand we don't want users to fall so far behind that they can't merge. On the other hand, we don't want to directly help users make coverage decisions.
